FROM nginx:alpine


# Заменяем дефолтную страницу nginx соответствующей веб-приложению
RUN rm -rf /usr/share/nginx/html/*
COPY /dist /usr/share/nginx/html
#COPY --from=builder /dist /usr/share/nginx/html

#COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]